name: Locality
main: com.github.download13.locality.Locality
version: 0.2
commands:
  g:
    description: Send global message
    usage: /g <message>
  h:
    description: Send help message to staff
    usage: /h <message>
  hg:
    description: Ask for help from the general population
    usage: /hg <message>
  s:
    description: Talk to other staff members
    usage: /s <message>
    permission: locality.staff
    permission-message: You must be a staff member to use Staff chat
permissions:
  locality.vip:
    description: Can have lower timeouts on Global and Help-Global
    default: false
  locality.staff:
    description: Can see help messages, can use and see Staff chat
    default: op